sudo: required
services:
    - docker

before_install:
    - docker build -t andrewleung01/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run andrewleung01/react-test npm test -- --coverage

after_success:
    - docker build -t andrewleung01/multi-client ./client
    - docker build -t andrewleung01/multi-nginx ./nginx
    - docker build -t andrewleung01/multi-worker ./worker
    - docker build -t andrewleung01/multi-server ./server

## Login docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin

## Push images to Docker hub
    - docker push andrewleung01/multi-client
    - docker push andrewleung01/multi-nginx
    - docker push andrewleung01/multi-worker
    - docker push andrewleung01/multi-server

