sudo: required
services:
    - docker

before_install:
    - docker build -t andrewleungiag/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run andrewleungiag/react-test npm test -- --coverage

after_success:
    - docker build -t andrewleungiag/multi-client ./client
    - docker build -t andrewleungiag/multi-nginx ./nginx
    - docker build -t andrewleungiag/multi-worker ./worker
    - docker build -t andrewleungiag/multi-server ./server

## Login docker CLI
    - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_ID" --password-stdin

## Push images to Docker hub
    - docker push andrewleungiag/multi-client
    - docker push andrewleungiag/multi-nginx
    - docker push andrewleungiag/multi-worker
    - docker push andrewleungiag/multi-server

